# Generated by Django 4.1.2 on 2023-03-05 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('_id', models.CharField(blank=True, max_length=10000)),
                ('action', models.CharField(blank=True, max_length=25)),
                ('action_date', models.DateField(default=datetime.datetime(2023, 3, 5, 5, 48, 33, 465438))),
            ],
        ),
    ]
