# Generated by Django 4.1.2 on 2023-03-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likesmodel',
            name='action_date',
        ),
    ]
