# Generated by Django 4.1.2 on 2023-03-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('bio', models.CharField(blank=True, default='', max_length=1080)),
                ('college', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default='', editable=False)),
                ('dob', models.CharField(blank=True, default='', max_length=25)),
                ('contact', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Choose not to say', 'Choose not to say')], default='Choose not to say', max_length=25)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('who_to_date', models.CharField(blank=True, choices=[('Male', 'Male'), ('Females', 'Females'), ('Anyone', 'Anyone')], default='Anyone', max_length=25)),
                ('height', models.IntegerField(blank=True, default='')),
                ('interests', models.CharField(blank=True, default='', max_length=10000)),
                ('is_drinker', models.BooleanField(blank=True, default=False)),
                ('is_smoker', models.BooleanField(blank=True, default=False)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
