# Generated by Django 4.1.2 on 2023-03-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.AddField(
            model_name='user',
            name='DateOfBirth',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
