# Generated by Django 4.1.2 on 2023-03-04 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_dob_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 3, 4), editable=False),
        ),
    ]
