# Generated by Django 4.1.2 on 2023-03-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Choose not to say', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='who_to_date',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Anyone', 'Anyone')], default='Anyone', max_length=25),
        ),
    ]
